
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_management_system
    username: root
    password: Subham@1997

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-MANAGEMENT

server:
  port: 8001


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka