

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_management_system
    username: root
    password: Subham@1997

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: REVIEW-MANAGEMENT

server:
  port: 8002


